# Generated by Django 5.2.9 on 2025-12-28 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название оборудования')),
                ('equipment_type', models.CharField(max_length=100, verbose_name='Тип оборудования')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('start_date', models.DateField(verbose_name='Дата ввода в эксплуатацию')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_period', models.IntegerField(verbose_name='ТО (мес.)')),
                ('tr_period', models.IntegerField(verbose_name='ТР (мес.)')),
                ('kr_period', models.IntegerField(verbose_name='КР (мес.)')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipment', verbose_name='Оборудования')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('ТО', 'Технический осмотр'), ('ТР', 'Технический ремонт'), ('КР', 'Капитальный ремонт')], max_length=2)),
                ('planned_date', models.DateField(verbose_name='Плановая дата')),
                ('status', models.CharField(default='Запланировано', max_length=20, verbose_name='Статус')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipment')),
            ],
        ),
    ]
